// Genere CLQ App Factory v2026.06.25-tts-polly-generative
const locations=[
    { name: "Place Saint-Lambert et Archéoforum", lat: 50.644942, lng: 5.573405, audio: "audio/Place_Saint_Lambert_et_Archeoforum.mp3", image: "images/points interets/Place_Saint_Lambert_et_Archeoforum.jpg", fallbackImage: "images/points interets/Place_Saint_Lambert_et_Archeoforum.svg" },
    { name: "Palais des Princes-Évêques", lat: 50.64626, lng: 5.573233, audio: "audio/Palais_des_Princes_Eveques.mp3", image: "images/points interets/Palais_des_Princes_Eveques.jpg", fallbackImage: "images/points interets/Palais_des_Princes_Eveques.svg" },
    { name: "Perron et place du Marché", lat: 50.64568428086098, lng: 5.575657923447444, audio: "audio/Perron_et_place_du_Marche.mp3", image: "images/points interets/Perron_et_place_du_Marche.jpg", fallbackImage: "images/points interets/Perron_et_place_du_Marche.svg" },
    { name: "Hôtel de Ville — La Violette", lat: 50.64517411316814, lng: 5.575768201659912, audio: "audio/Hotel_de_Ville_La_Violette.mp3", image: "images/points interets/Hotel_de_Ville_La_Violette.jpg", fallbackImage: "images/points interets/Hotel_de_Ville_La_Violette.svg" },
    { name: "Rue Hors-Château", lat: 50.64731804356458, lng: 5.579179566080553, audio: "audio/Rue_Hors_Chateau.mp3", image: "images/points interets/Rue_Hors_Chateau.jpg", fallbackImage: "images/points interets/Rue_Hors_Chateau.svg" },
    { name: "Montagne de Bueren", lat: 50.64812890834167, lng: 5.577375959743035, audio: "audio/Montagne_de_Bueren.mp3", image: "images/points interets/Montagne_de_Bueren.jpg", fallbackImage: "images/points interets/Montagne_de_Bueren.svg" },
    { name: "Coteaux de la Citadelle", lat: 50.647325310108364, lng: 5.574371473184764, audio: "audio/Coteaux_de_la_Citadelle.mp3", image: "images/points interets/Coteaux_de_la_Citadelle.jpg", fallbackImage: "images/points interets/Coteaux_de_la_Citadelle.svg" },
    { name: "Collégiale Saint-Barthélemy", lat: 50.647839, lng: 5.582631, audio: "audio/Collegiale_Saint_Barthelemy.mp3", image: "images/points interets/Collegiale_Saint_Barthelemy.jpg", fallbackImage: "images/points interets/Collegiale_Saint_Barthelemy.svg" },
    { name: "Grand Curtius", lat: 50.647263, lng: 5.583276, audio: "audio/Grand_Curtius.mp3", image: "images/points interets/Grand_Curtius.jpg", fallbackImage: "images/points interets/Grand_Curtius.svg" },
    { name: "Quai de Maestricht et bord de Meuse", lat: 50.649392, lng: 5.598143, audio: "audio/Quai_de_Maestricht_et_bord_de_Meuse.mp3", image: "images/points interets/Quai_de_Maestricht_et_bord_de_Meuse.jpg", fallbackImage: "images/points interets/Quai_de_Maestricht_et_bord_de_Meuse.svg" },
    { name: "Collégiale Saint-Denis", lat: 50.64264, lng: 5.574799, audio: "audio/Collegiale_Saint_Denis.mp3", image: "images/points interets/Collegiale_Saint_Denis.jpg", fallbackImage: "images/points interets/Collegiale_Saint_Denis.svg" },
    { name: "Passage Lemonnier", lat: 50.64195, lng: 5.571093, audio: "audio/Passage_Lemonnier.mp3", image: "images/points interets/Passage_Lemonnier.jpg", fallbackImage: "images/points interets/Passage_Lemonnier.svg" },
    { name: "Le Carré", lat: 50.642103, lng: 5.569436, audio: "audio/Le_Carre.mp3", image: "images/points interets/Le_Carre.jpg", fallbackImage: "images/points interets/Le_Carre.svg" },
    { name: "Opéra Royal de Wallonie", lat: 50.643545, lng: 5.570594, audio: "audio/Opera_Royal_de_Wallonie.mp3", image: "images/points interets/Opera_Royal_de_Wallonie.jpg", fallbackImage: "images/points interets/Opera_Royal_de_Wallonie.svg" },
    { name: "Cité Miroir", lat: 50.643283, lng: 5.568073, audio: "audio/Cite_Miroir.mp3", image: "images/points interets/Cite_Miroir.jpg", fallbackImage: "images/points interets/Cite_Miroir.svg" },
    { name: "Cathédrale Saint-Paul", lat: 50.640393, lng: 5.571873, audio: "audio/Cathedrale_Saint_Paul.mp3", image: "images/points interets/Cathedrale_Saint_Paul.jpg", fallbackImage: "images/points interets/Cathedrale_Saint_Paul.svg" },
    { name: "Université de Liège — place du XX Août", lat: 50.640918, lng: 5.57617, audio: "audio/Universite_de_Liege_place_du_XX_Aout.mp3", image: "images/points interets/Universite_de_Liege_place_du_XX_Aout.jpg", fallbackImage: "images/points interets/Universite_de_Liege_place_du_XX_Aout.svg" },
    { name: "Passerelle Saucy et Outremeuse", lat: 50.641256, lng: 5.577946, audio: "audio/Passerelle_Saucy_et_Outremeuse.mp3", image: "images/points interets/Passerelle_Saucy_et_Outremeuse.jpg", fallbackImage: "images/points interets/Passerelle_Saucy_et_Outremeuse.svg" },
    { name: "La Batte", lat: 50.645596, lng: 5.5807, audio: "audio/La_Batte.mp3", image: "images/points interets/La_Batte.jpg", fallbackImage: "images/points interets/La_Batte.svg" },
    { name: "Église Saint-Jacques", lat: 50.636972, lng: 5.570208, audio: "audio/Eglise_Saint_Jacques.mp3", image: "images/points interets/Eglise_Saint_Jacques.jpg", fallbackImage: "images/points interets/Eglise_Saint_Jacques.svg" },
    { name: "Parc d’Avroy et Trinkhall", lat: 50.633848, lng: 5.568494, audio: "audio/Parc_d_Avroy_et_Trinkhall.mp3", image: "images/points interets/Parc_d_Avroy_et_Trinkhall.jpg", fallbackImage: "images/points interets/Parc_d_Avroy_et_Trinkhall.svg" },
    { name: "Gare de Liège-Guillemins", lat: 50.6246, lng: 5.5669, audio: "audio/Gare_de_Liege_Guillemins.mp3", image: "images/points interets/Gare_de_Liege_Guillemins.jpg", fallbackImage: "images/points interets/Gare_de_Liege_Guillemins.svg" },
    { name: "Pont de Fragnée", lat: 50.620914, lng: 5.57936, audio: "audio/Pont_de_Fragnee.mp3", image: "images/points interets/Pont_de_Fragnee.jpg", fallbackImage: "images/points interets/Pont_de_Fragnee.svg" },
    { name: "Parc de la Boverie", lat: 50.62909, lng: 5.576884, audio: "audio/Parc_de_la_Boverie.mp3", image: "images/points interets/Parc_de_la_Boverie.jpg", fallbackImage: "images/points interets/Parc_de_la_Boverie.svg" },
    { name: "Musée de La Boverie", lat: 50.627448, lng: 5.577579, audio: "audio/Musee_de_La_Boverie.mp3", image: "images/points interets/Musee_de_La_Boverie.jpg", fallbackImage: "images/points interets/Musee_de_La_Boverie.svg" },
    { name: "Passerelle La Belle Liégeoise", lat: 50.628142, lng: 5.57436, audio: "audio/Passerelle_La_Belle_Liegeoise.mp3", image: "images/points interets/Passerelle_La_Belle_Liegeoise.jpg", fallbackImage: "images/points interets/Passerelle_La_Belle_Liegeoise.svg" }
];
const availableCircuits=["petit","moyen","grand"];
const circuits={"petit":[1,2,3,4,5,6,7,8,9,10,1],"petit_gare":[1,2,3,4,5,6,7,8,9,10,1],"moyen":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1],"moyen_gare":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1],"grand":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,1],"grand_gare":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,1]};
const circuitEstimates={"petit":{"distanceKm":3.6,"walkingTimeMinutes":58,"listeningTimeMinutes":55,"totalTimeMinutes":113},"moyen":{"distanceKm":6.3,"walkingTimeMinutes":100,"listeningTimeMinutes":110,"totalTimeMinutes":210},"grand":{"distanceKm":9.4,"walkingTimeMinutes":148,"listeningTimeMinutes":135,"totalTimeMinutes":283}};
